---
title: "The Office Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(ggrepel)

lines <- read.csv('The-Office-Lines-V3.csv')
#Clean Up Character Names, fix casing, remove whitespace, and remove punctuation
lines$speaker <- str_to_title(tolower(trimws(gsub('[[:punct:]]+', "", lines$speaker))))

#Identify main characters
# test
mainCharacters <- lines %>% 
  group_by(speaker) %>%
  summarise(line_count = n()) %>%
  arrange(desc(line_count)) %>%
  top_n(n = 30, line_count)


# How many times did they share a scene with which characters - GM
character_selected <- 'Jim'

#characters_wide <-  
  lines %>% 
    group_by(season, episode, scene, speaker) %>%
    summarise(in_scene = TRUE) %>%
    pivot_wider(id_cols = c('season', 'episode', 'scene'), names_from = speaker, values_from = in_scene, values_fill = FALSE)

lines %>%
  filter(speaker == character_selected) %>%
  select(season, episode, scene) %>% 
  unique()




```

Characters {data-icon="fa-user-friends"}
===

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}


```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```










Seasons {data-icon="fa-tv"}
===

### Chart A

```{r}

## scatter of total lines by character in season 1 vs season 9
lines$count <- 1

seasonStart <- 1 #make filter
seasonEnd <- 9   #make filter

topChar <- lines %>% 
    filter(season %in% c(seasonStart, seasonEnd)) %>%
    count(speaker, sort = TRUE)
    
top <- top_n(topChar, 20)

episodeSummary <- lines %>% 
  group_by(season, episode, speaker) %>% 
  summarize(total_lines = sum(count)) %>%
  filter(speaker %in% top$speaker)



#average lines per episode of season
sStart <- episodeSummary %>% 
  filter( season == 1) %>%
  group_by(speaker) %>% 
  summarize(total_lines = mean(total_lines)) 

sEnd <- episodeSummary %>% 
  filter( season == 9) %>% 
  group_by(speaker) %>% 
  summarize(total_lines = mean(total_lines)) 


scatter <- merge(sStart,sEnd, by.x = 'speaker', by.y = 'speaker',all=FALSE) 
lineMax <- max(scatter$total_lines.x, scatter$total_lines.y)+1

ggplot(scatter, aes(x = total_lines.x, y = total_lines.y)) + 
  geom_point() + 
  labs(title = "Average # of Lines Per Episode", subtitle = "First Season vs Last Season", caption = "Excludes Michael since he was no longer on the show") + 
  scale_x_continuous("First Season", expand = c(0, 0), limits = c(0,lineMax)) + 
  scale_y_continuous("Last Season", expand = c(0, 0), limits = c(0,lineMax)) +
  geom_abline(intercept = 0, slope = 1, color="#001ca8", linetype="dashed", size=.4) +
  geom_text_repel(aes(label = speaker), size = 3) +
  theme_bw() + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor =   element_blank(), axis.line = element_line(colour = "black")) +      theme(plot.title=element_text(size=18, hjust=.5, face="bold", colour="black", vjust=-1)) +
  theme(plot.subtitle=element_text(size=11, hjust=0.5,  colour="black", vjust=-1)) 


```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

#season filter
selectedSeason <- 1

topChar <- lines %>% 
    filter(season == selectedSeason) %>%
    count(speaker, sort = TRUE) 
    

top <- top_n(topChar, 5)

totLines <- lines %>%
            filter(season == selectedSeason) %>%  
            filter(speaker %in% top$speaker) %>% 
            group_by(season, speaker, episode) %>% 
            summarize(total_lines = sum(count)) 

totLines$SeasonEpisode <- paste(totLines$season, ":", totLines$episode) #get rid of space 

ggplot(totLines, aes(x = SeasonEpisode, y = total_lines,fill = speaker,group = speaker,color = speaker )) + 
  geom_line( size = .5) + 
  labs(title = "Total Lines by Season", subtitle = "", caption = "") + 
  #scale_x_continuous("Season", breaks=c(1,2,3,4,5,6,7,8,9) , expand = c(0, 0)) + 
  scale_x_discrete("Season - Episode") +
  scale_y_continuous("Number of Lines", expand = c(0, 0)) +
  theme_bw() + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor =      element_blank(), axis.line = element_line(colour = "black")) +      theme(plot.title=element_text(size=18, hjust=.5, face="bold", colour="black", vjust=-1)) +
  theme(plot.subtitle=element_text(size=11, hjust=0.5,  colour="black", vjust=-1)) 


```

### Chart C

```{r}

```