---
title: "Data_Processing"
author: ""
date: "10/31/2020"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(ggrepel)
lines <- read.csv('The-Office-Lines-V3.csv')
#Clean Up Character Names, fix casing, remove whitespace, and remove punctuation
lines$speaker <- str_to_title(tolower(trimws(gsub('[[:punct:]]+', "", lines$speaker))))

```

#Only Brainstorming so far

```{r}
#Identify main characters

mainCharacters <- lines %>% 
  group_by(speaker) %>%
  summarise(line_count = n()) %>%
  arrange(desc(line_count)) %>%
  top_n(n = 30, line_count)




# How many times did they share a scene with which characters - GM
character_selected <- 'Jim'

#characters_wide <-  
  lines %>% 
    group_by(season, episode, scene, speaker) %>%
    summarise(in_scene = TRUE) %>%
    pivot_wider(id_cols = c('season', 'episode', 'scene'), names_from = speaker, values_from = in_scene, values_fill = FALSE)

lines %>%
  filter(speaker == character_selected) %>%
  select(season, episode, scene) %>% 
  unique()

# WHat is the sentiment of different characters? Does it shift over time? - GM
```


## Episode Profiles
```{r}
# What's the main topic of the episode?
# How many times does Michael say 'That's what she said'

```


## Character Proflies - DM
```{r}
## scatter of total lines by character in season 1 vs season 9
lines$count <- 1

episodeSummary <- lines %>% 
  group_by(season, episode, speaker) %>% 
  summarize(total_lines = sum(count)) %>%
  filter(speaker != 'Michael')

#average lines per episode of season
s1 <- episodeSummary %>% 
  filter( season == 1) %>%
  group_by(speaker) %>% 
  summarize(total_lines = mean(total_lines)) 

s9 <- episodeSummary %>% 
  filter( season == 9) %>% 
  group_by(speaker) %>% 
  summarize(total_lines = mean(total_lines)) 


scatter <- merge(s1,s9, by.x = 'speaker', by.y = 'speaker',all=FALSE) 
lineMax <- max(scatter$total_lines.x, scatter$total_lines.y)+1

ggplot(scatter, aes(x = total_lines.x, y = total_lines.y)) + 
  geom_point() + 
  labs(title = "Average # of Lines Per Episode", subtitle = "First Season vs Last Season", caption = "Excludes Michael since he was no longer on the show") + 
  scale_x_continuous("First Season", expand = c(0, 0), limits = c(0,lineMax)) + 
  scale_y_continuous("Last Season", expand = c(0, 0), limits = c(0,lineMax)) +
  geom_abline(intercept = 0, slope = 1, color="#001ca8", linetype="dashed", size=.4) +
  geom_text_repel(aes(label = speaker), size = 3) +
  theme_bw() + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor =   element_blank(), axis.line = element_line(colour = "black")) +      theme(plot.title=element_text(size=18, hjust=.5, face="bold", colour="black", vjust=-1)) +
  theme(plot.subtitle=element_text(size=11, hjust=0.5,  colour="black", vjust=-1)) 


```

```{r}
# total lines over each season/episode (maybe make character a filter on dashboard?) - DM

topChar <- lines %>% count(speaker, sort = TRUE)
top10 <- top_n(linesperCharacter, 6)

totLines <- lines %>%
            filter(speaker %in% top10$speaker) %>%  
            group_by(season, speaker) %>% 
            summarize(total_lines = sum(count)) 

ggplot(totLines, aes(x = season, y = total_lines,fill = speaker,group = speaker,color = speaker )) + 
  geom_line( size = .5) + 
  labs(title = "Total Lines by Season", subtitle = "", caption = "") + 
  scale_x_continuous("Season", breaks=c(1,2,3,4,5,6,7,8,9) , expand = c(0, 0)) + 
  scale_y_continuous("Number of Lines", expand = c(0, 0)) +
  theme_bw() + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor =      element_blank(), axis.line = element_line(colour = "black")) +      theme(plot.title=element_text(size=18, hjust=.5, face="bold", colour="black", vjust=-1)) +
  theme(plot.subtitle=element_text(size=11, hjust=0.5,  colour="black", vjust=-1)) 


#count <- grepl("|what she said|", lines$line)


```




```{r}
# How many lines does each character have? - ER
linesperCharacter <- lines %>% 
  count(speaker, sort = TRUE)
top10LinesChar <- top_n(linesperCharacter, 10)

ggplot(top10LinesChar, aes(x = reorder(speaker,n), y = n, fill = factor(speaker))) + 
    stat_summary_bin(fun.y=sum, geom="bar", alpha = .7, position = position_dodge(0.95)) +
  labs(title = "Which characters had the most lines?") +
    geom_text(data = top10LinesChar, aes(label = scales::comma(n,2)), size = 3, vjust=1, position = position_dodge(width = 1))+
    labs(x = "Character", y = "# of Lines") +
  theme(plot.title = element_text(size = 15, color = "#22292F", face = "bold", hjust = 0.5), panel.background = element_blank(), legend.position = "none", axis.ticks = element_blank()) +
coord_flip()
```

```{r}
# How many scenes were the characters in - ER
CharSceneCount <- lines %>%
  group_by(speaker) %>%
  summarise(SceneCount = n_distinct(scene))
CharSceneCountSort <- CharSceneCount %>% arrange(desc(SceneCount))
top10ScenesChar <- top_n(CharSceneCountSort, 10)


gg_dot <- top10ScenesChar %>%
  arrange(SceneCount) %>%
  mutate(speaker = fct_inorder(speaker)) %>%
  
  ggplot() +
  theme_classic() +
  theme(axis.title = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line = element_blank(),
        plot.title = element_text(size = 15, color = "#22292F", face = "bold", hjust = 0.5)) +
  geom_point(aes(x = 12, y = speaker), 
             size = 0, col = "white") + 
  geom_hline(yintercept = 1:10, col = "grey80") +
  geom_point(aes(x = SceneCount, y = speaker), 
             size = 11, col = "#9DBEBB")+ 
  geom_text(aes(x = SceneCount, y = speaker, 
                label = paste0(round(SceneCount, 1))),
            col = "black") +
  scale_color_manual(values = c("#9DBEBB"), guide = "none") +
  scale_y_discrete(expand = c(0.2, 0)) +
  labs(title = "How Many Scenes Were the Characters In?", x = "Total Scene Count", y = "Characters")
gg_dot
```

```{r}
# Average Number of scenes per season - ER
EpsScnCount <- lines %>%
  group_by(season) %>%
  summarise(NumEps = n_distinct(episode), NumScene = n_distinct(scene))

AvgScnPerEps <- EpsScnCount %>%
  group_by(season) %>%
  summarise(AvgScnEps = round(NumScene/NumEps))
```

```{r}
# How many words in each line - ER
wordCount <- unnest_tokens(lines, input=line, output=word,
  format="text", token="words", drop=FALSE, to_lower=TRUE)
wordCountperLine <- wordCount %>%
  filter(speaker %in% c("Michael", "Dwight", "Jim", "Pam", "Andy", "Angela", "Erin", "Kevin", "Oscar", "Ryan")) %>%
  group_by(speaker, line) %>%
    summarise(NumWords = length(word))

ggplot(wordCountperLine, aes(x=reorder(speaker,NumWords), y=NumWords, fill = factor(speaker))) + geom_boxplot()  +
  labs(title = "How Many Words Per Line Does Each Character Have?", x = "Character", y = "# of Words") +
  theme(plot.title = element_text(size = 15, color = "#22292F", face = "bold", hjust = 0.5), panel.background = element_blank(), legend.position = "none", axis.ticks = element_blank()) +
coord_flip()
```

